name: Aggiorna catalogo libri

on:
  schedule:
    - cron: '0 4 * * *'  # Ogni giorno alle 04:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          with:
          python-version: 3.10

      - name: Installa dipendenze
        run: pip install requests beautifulsoup4

      - name: Esegui scraper
        run: python scripts/scraper.py

      - name: Commit e push aggiornamento
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Aggiornamento automatico del catalogo del $(date '+%Y-%m-%d')" || echo "Nessuna modifica"
          git push
